"""Days of the week in the shift

Revision ID: 23913f9fd8ba
Revises: 51c3856e4c29
Create Date: 2026-03-12 21:06:56.770955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23913f9fd8ba'
down_revision = '51c3856e4c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_shift', schema=None) as batch_op:
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###
