"""test model sync

Revision ID: 43cc6a5c8326
Revises: c85bb491b5be
Create Date: 2026-02-28 10:59:28.541709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cc6a5c8326'
down_revision = 'c85bb491b5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deduction_bracket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deduction_id', sa.Integer(), nullable=False),
    sa.Column('salary_from', sa.Float(), nullable=False),
    sa.Column('salary_to', sa.Float(), nullable=False),
    sa.Column('employee_share', sa.Float(), nullable=True),
    sa.Column('employer_share', sa.Float(), nullable=True),
    sa.Column('ec', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('fixed_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deduction_id'], ['deduction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_deduction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_id', sa.Integer(), nullable=False),
    sa.Column('deduction_name', sa.String(length=100), nullable=True),
    sa.Column('employee_share', sa.Float(), nullable=True),
    sa.Column('employer_share', sa.Float(), nullable=True),
    sa.Column('ec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payroll_id'], ['payroll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deduction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('calculation_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ceiling', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('floor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('min_salary')
        batch_op.drop_column('max_salary')

    with op.batch_alter_table('employee_deductions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('override_amount', sa.Float(), nullable=True))
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('deduction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('amount')

    with op.batch_alter_table('tax', schema=None) as batch_op:
        batch_op.drop_column('fixed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fixed', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('employee_deductions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=True))
        batch_op.alter_column('deduction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('override_amount')

    with op.batch_alter_table('deduction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_salary', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('min_salary', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('floor')
        batch_op.drop_column('ceiling')
        batch_op.drop_column('rate')
        batch_op.drop_column('calculation_type')
        batch_op.drop_column('description')

    op.drop_table('payroll_deduction')
    op.drop_table('deduction_bracket')
    # ### end Alembic commands ###
