""" employee deductions

Revision ID: a19724d7dbd7
Revises: b0f7bcd73110
Create Date: 2026-02-18 11:42:32.470884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19724d7dbd7'
down_revision = 'b0f7bcd73110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_salary', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_salary', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowance', schema=None) as batch_op:
        batch_op.drop_column('max_salary')
        batch_op.drop_column('min_salary')

    # ### end Alembic commands ###
