"""loan_type and provider

Revision ID: aee1474593f5
Revises: 0f64608adc4d
Create Date: 2026-03-16 17:37:38.615555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee1474593f5'
down_revision = '0f64608adc4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('loan_type', sa.String(length=100), nullable=True))
        batch_op.drop_column('loan_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('loan_type')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
