"""status in payslip

Revision ID: b0141988e844
Revises: dfc840093929
Create Date: 2026-03-08 23:47:41.242554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0141988e844'
down_revision = 'dfc840093929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours_worked', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('days_worked', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_column('days_worked')
        batch_op.drop_column('hours_worked')

    # ### end Alembic commands ###
