"""dynamic employee deductions

Revision ID: b0f7bcd73110
Revises: f52ba026fb48
Create Date: 2026-02-18 11:28:25.650139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f7bcd73110'
down_revision = 'f52ba026fb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deduction', schema=None) as batch_op:
        batch_op.drop_column('amount')

    with op.batch_alter_table('employee_deductions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_column('tax')
        batch_op.drop_column('sss')
        batch_op.drop_column('philhealth')
        batch_op.drop_column('pagibig')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagibig', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('philhealth', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('sss', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('employee_deductions', schema=None) as batch_op:
        batch_op.drop_column('active')
        batch_op.drop_column('amount')

    with op.batch_alter_table('deduction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
