"""fix payroll architecture

Revision ID: b6233ec44fed
Revises: 1c7e3c79c57c
Create Date: 2026-02-28 11:58:33.956376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6233ec44fed'
down_revision = '1c7e3c79c57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deduction', schema=None) as batch_op:
        batch_op.drop_column('max_salary')
        batch_op.drop_column('min_salary')

    with op.batch_alter_table('employee_deductions', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_deductions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('deduction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_salary', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('max_salary', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
