"""Shifts status

Revision ID: b883ea40cf4f
Revises: 23913f9fd8ba
Create Date: 2026-03-12 21:36:02.463570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b883ea40cf4f'
down_revision = '23913f9fd8ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_shift', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
