""" employee deductions

Revision ID: c168c3ad9e33
Revises: a19724d7dbd7
Create Date: 2026-02-18 15:48:56.916786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c168c3ad9e33'
down_revision = 'a19724d7dbd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deduction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_salary', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_salary', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deduction', schema=None) as batch_op:
        batch_op.drop_column('max_salary')
        batch_op.drop_column('min_salary')

    # ### end Alembic commands ###
