"""Cancel Leave

Revision ID: c8e28fe891c4
Revises: f6dc1fa39367
Create Date: 2026-04-06 20:56:11.849275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e28fe891c4'
down_revision = 'f6dc1fa39367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canceled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_column('canceled_at')

    # ### end Alembic commands ###
