"""empty message

Revision ID: cdf629c84a1f
Revises: b883ea40cf4f
Create Date: 2026-03-13 09:49:23.130501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf629c84a1f'
down_revision = 'b883ea40cf4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unpaid_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('leave_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_paid_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_duration_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_type', schema=None) as batch_op:
        batch_op.drop_column('max_duration_days')
        batch_op.drop_column('max_paid_days')

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_column('unpaid_days')
        batch_op.drop_column('paid_days')

    # ### end Alembic commands ###
