"""Add OTP fields to User

Revision ID: f6dc1fa39367
Revises: 07a46536186e
Create Date: 2026-04-06 20:23:49.158354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6dc1fa39367'
down_revision = '07a46536186e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('otp_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('otp_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_verified')
        batch_op.drop_column('otp_expiry')
        batch_op.drop_column('otp_code')

    # ### end Alembic commands ###
